using System.Collections.Generic;
using UnityEngine;


///Controls ball movement, time, path visualization and control buttons
public class BallController : MonoBehaviour
{
   
    public PathfindingType pathfindingType;
    public float moveSpeed = 3f;

    
    private MazeManager maze;
    private List<Vector2Int> path;
    private int currentIndex = 0;

    //Execution control
    private bool canMove = false;
    private bool finished = false;

    //Time
    private float startTime;
    public float ElapsedTime { get; private set; }

    //Path visual
    private LineRenderer lineRenderer;
    private bool showPath = false;

    private bool isPaused = false;

    void Start()
    {
        maze = FindObjectOfType<MazeManager>();
        pathfindingType = GameManager.Instance.selectedAI;

        Pathfinding pathfinding = new Pathfinding(maze);
        path = pathfinding.FindPath(
            maze.startPoint,
            maze.endPoint,
            pathfindingType
        );

        if (path == null || path.Count <= 1)
            return;

        transform.position = maze.CellToWorld(path[0]);

        SetupLineRenderer();
        DrawPath();
        lineRenderer.enabled = false;
    }

    void Update()
    {
        if (!canMove || path == null || finished || isPaused)
            return;

        ElapsedTime += Time.deltaTime;
        MoveAlongPath();
    }

   
    // MOVEMENT
 
    //Move the ball along the calculated path
    private void MoveAlongPath()
    {
        if (currentIndex >= path.Count)
            return;
        
        Vector3 target = maze.CellToWorld(path[currentIndex]);
        transform.position = Vector3.MoveTowards(
            transform.position,
            target,
            moveSpeed * Time.deltaTime
        );

        if (Vector3.Distance(transform.position, target) < 0.01f)
        {
            currentIndex++;

            if (currentIndex >= path.Count)
            {
                finished = true;
                //Debug.Log($"Tempo total: {ElapsedTime:F2} segundos");
            }
        }
    }

    
    // BOTTONS
 
    
    public void StartBall()
    {
        if (path == null || path.Count <= 1)
            return;

        canMove = true;
        finished = false;
        startTime = Time.time;
    }

    public void TogglePause()
    {
        isPaused = !isPaused;
    }

    public void Restart()
    {
        canMove = false;
        finished = false;
        currentIndex = 0;
        ElapsedTime = 0f;

        transform.position = maze.CellToWorld(path[0]);
    }


    public void TogglePath()
    {
        showPath = !showPath;
        lineRenderer.enabled = showPath;
    }


    // PATH

    //Setup the LineRennderer to draw the path
    private void SetupLineRenderer()
    {
        lineRenderer = gameObject.AddComponent<LineRenderer>();
        lineRenderer.positionCount = path.Count;
        lineRenderer.widthMultiplier = 0.1f;

        lineRenderer.material = new Material(Shader.Find("Sprites/Default"));
        lineRenderer.startColor = Color.green;
        lineRenderer.endColor = Color.green;
    }

    //Draw the path in LineRenderer
    private void DrawPath()
    {
        for (int i = 0; i < path.Count; i++)
        {
            Vector3 pos = maze.CellToWorld(path[i]);
            pos.z = -0.1f;
            lineRenderer.SetPosition(i, pos);
        }
    }
}

/*
HOW THIS SCRIPT WORKS:
This script controls the movement of the ball inside the maze
It receives a path generated by the Pathfinding system and moves the ball step by step
from the start cell to the end cell. The movement is grid-based and respects the maze
walls by querying the MazeManager before moving to a new cell
*/